/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const differenceInDays: typeof import('date-fns/esm')['differenceInDays']
  const formatDistance: typeof import('date-fns/esm')['formatDistance']
  const parseISO: typeof import('date-fns/esm')['parseISO']
}
